/**
 * Noisee - Ambient Sound Studio
 * Vanilla JavaScript Audio Engine & UI Controller
 */

(() => {
  'use strict';

  // --- Sound Definitions ---
  // src: null + synthesized: true  →  generated by Web Audio API (no file needed)
  const SOUNDS_DEF = [
    { id: 'rain',        icon: '🌧️', name: 'Rain',        src: 'assets/sounds/rain.mp3',    defaultVol: 0.6 },
    { id: 'river',       icon: '🏞️', name: 'River',       src: 'assets/sounds/river.mp3',   defaultVol: 0.5 },
    { id: 'wind',        icon: '🌬️', name: 'Wind',        src: 'assets/sounds/wind.mp3',    defaultVol: 0.4 },
    { id: 'fire',        icon: '🔥', name: 'Fire',        src: 'assets/sounds/bonfire.mp3', defaultVol: 0.7 },
    { id: 'birds',       icon: '🦜', name: 'Birds',       src: 'assets/sounds/birds.mp3',   defaultVol: 0.5 },
    { id: 'night-birds', icon: '🦉', name: 'Night Birds', src: 'assets/sounds/owl.mp3',     defaultVol: 0.4 },
    { id: 'cicada',      icon: '🦗', name: 'Cicada',      src: 'assets/sounds/cicada.mp3',  defaultVol: 0.3 },
    { id: 'sea',         icon: '🌊', name: 'Sea',         src: 'assets/sounds/sea.mp3',     defaultVol: 0.6 },
    // New sounds — drop matching files into assets/sounds/ and they light up
    { id: 'thunder',     icon: '⛈️', name: 'Thunder',     src: 'assets/sounds/thunder.mp3', defaultVol: 0.65 },
    { id: 'forest',      icon: '🌿', name: 'Forest',      src: 'assets/sounds/forest.mp3',  defaultVol: 0.5 },
    { id: 'train',       icon: '🚂', name: 'Train',       src: 'assets/sounds/train.mp3',   defaultVol: 0.4 },
    // Synthesized — no file required, generated in Web Audio API
    { id: 'brown-noise', icon: '〰️', name: 'Brown Noise', src: null, synthesized: true,     defaultVol: 0.5 },
  ];

  // --- Built-in Presets ---
  const BUILTIN_PRESETS = {
    'Cozy Fireplace':    { fire: 0.7, cicada: 0.3, 'night-birds': 0.35, wind: 0.15 },
    'Gentle Rain':       { rain: 0.6, wind: 0.15 },
    'Rainy Night':       { rain: 0.75, river: 0.3, wind: 0.25, cicada: 0.2 },
    'Tropical Beach':    { sea: 0.75, birds: 0.8, river: 0.3, wind: 0.15 },
    'Thunderstorm':      { rain: 0.9, wind: 0.75, river: 0.4 },
    'Summer Night':      { cicada: 0.8, 'night-birds': 0.6, fire: 0.35, river: 0.2 },
    'Forest Campfire':   { fire: 0.85, birds: 0.6, cicada: 0.5, 'night-birds': 0.35 },
    'Windy River':       { river: 0.85, wind: 0.45 },
    'Beach Day':         { sea: 0.8, birds: 0.5, wind: 0.2 },
    'Night Swamp':       { cicada: 0.85, 'night-birds': 0.6, river: 0.5, sea: 0.15 },
    // New presets
    'Deep Focus':        { 'brown-noise': 0.7, rain: 0.25 },
    'Storm Sleep':       { thunder: 0.7, rain: 0.5, wind: 0.3 },
    'Forest Morning':    { forest: 0.7, birds: 0.5, river: 0.25 },
    'Train Journey':     { train: 0.75, rain: 0.3 },
    'Brown Rain':        { 'brown-noise': 0.5, rain: 0.45, wind: 0.2 },
  };

  // IDs to eagerly pre-fetch during browser idle (smallest files first)
  const IDLE_PRELOAD_IDS = ['cicada', 'fire', 'rain', 'river'];

  // --- Audio state ---
  let audioCtx     = null;
  let masterGain   = null;
  let analyserNode = null;
  let sounds       = {};
  let customPresets  = {};
  let activeMixCache = [];
  let isMuted      = false;
  let prevVolume   = 0.5;
  let soloMode     = null;

  // Sleep timer state
  let sleepTimerInterval = null;
  let sleepTimerEndsAt   = null;
  let sleepInitialVol    = null;

  // Pomodoro — timestamp-based
  let pomodoroInterval         = null;
  let pomodoroTimeLeft         = 25 * 60;
  let pomodoroRemainingAtPause = 25 * 60;
  let pomodoroStartTime        = null;
  let pomodoroMode             = 'work';

  // Cached DOM references
  let dom = {};

  // --- LocalStorage Keys ---
  const LS_VOL            = 'noisee_master_vol';
  const LS_ORDER          = 'noisee_sound_order';
  const LS_CUSTOM_PRESETS = 'noisee_custom_presets';
  const LS_THEME          = 'noisee_theme';
  const LS_SOUND_VOLS     = 'noisee_sound_vols';
  const LS_SKIN           = 'noisee_skin';

  // =========================================================================
  // Audio Context — lazy, only created on first user gesture
  // =========================================================================

  function getAudioContext() {
    if (!audioCtx) {
      const AudioCtxClass = window.AudioContext || window.webkitAudioContext;
      audioCtx = new AudioCtxClass();

      masterGain = audioCtx.createGain();
      const sliderVal = dom.masterVolume ? parseFloat(dom.masterVolume.value) : null;
      const savedVol  = localStorage.getItem(LS_VOL);
      const initVol   = sliderVal !== null ? sliderVal
                        : savedVol !== null ? parseFloat(savedVol) : 0.5;
      masterGain.gain.setValueAtTime(initVol, audioCtx.currentTime);

      analyserNode = audioCtx.createAnalyser();
      analyserNode.fftSize = 128;
      analyserNode.smoothingTimeConstant = 0.8;

      masterGain.connect(analyserNode);
      analyserNode.connect(audioCtx.destination);

      initVisualizer();
    }
    if (audioCtx.state === 'suspended') audioCtx.resume();
    return audioCtx;
  }

  // =========================================================================
  // Lazy GainNode creation per sound
  // =========================================================================

  function ensureSoundGain(id) {
    const s = sounds[id];
    if (!s || s.gain) return;
    const ctx = getAudioContext();
    s.gain = ctx.createGain();
    const effectiveVol = (soloMode !== null && soloMode !== id) ? 0 : s.vol;
    s.gain.gain.setValueAtTime(effectiveVol, ctx.currentTime);
    s.gain.connect(masterGain);
  }

  // =========================================================================
  // Brown Noise Synthesizer — no file, pure Web Audio API
  // =========================================================================

  function createBrownNoiseBuffer(ctx) {
    const duration   = 20; // 20-second stereo loop
    const sampleRate = ctx.sampleRate;
    const frameCount = sampleRate * duration;
    const buffer     = ctx.createBuffer(2, frameCount, sampleRate);
    const fadeFrames = Math.floor(sampleRate * 0.08); // 80ms crossfade at loop point

    for (let ch = 0; ch < 2; ch++) {
      const data = buffer.getChannelData(ch);
      let lastOut = 0;

      for (let i = 0; i < frameCount; i++) {
        const white = Math.random() * 2 - 1;
        lastOut = (lastOut + 0.02 * white) / 1.02;
        data[i] = lastOut * 3.5;
      }

      // Smooth the loop boundary to eliminate clicks
      for (let i = 0; i < fadeFrames; i++) {
        const t = i / fadeFrames;
        // Fade out the last `fadeFrames` frames
        data[frameCount - fadeFrames + i] *= (1 - t);
        // Blend with the start of the buffer for a seamless loop
        data[frameCount - fadeFrames + i] += data[i] * t;
      }
    }
    return buffer;
  }

  // =========================================================================
  // Sound Playback — handles file-based, pre-fetched raw buffer, synthesized
  // =========================================================================

  async function toggleSound(s, forceState = null) {
    ensureSoundGain(s.id);
    const ctx = getAudioContext();
    const shouldPlay = forceState !== null ? forceState : !s.playing;
    if (shouldPlay === s.playing) return;

    if (shouldPlay) {
      if (!s.buffer) {
        if (s.synthesized) {
          // Synthesized sound — generate instantly, no loading spinner
          s.buffer = createBrownNoiseBuffer(ctx);
        } else {
          s.playBtn.classList.add('loading');
          try {
            let rawBuf;
            if (s._rawBuffer) {
              // ✅ Use idle-preloaded bytes — skip the network fetch entirely
              rawBuf      = s._rawBuffer;
              s._rawBuffer = null; // free reference; decoded buffer takes over
            } else {
              const resp = await fetch(s.src);
              rawBuf     = await resp.arrayBuffer();
            }
            s.buffer = await ctx.decodeAudioData(rawBuf);
          } catch (err) {
            console.error(`Failed to load ${s.name}:`, err);
            showToast(`Error loading ${s.name} — check the file exists`);
            s.playBtn.classList.remove('loading');
            return;
          } finally {
            s.playBtn.classList.remove('loading');
          }
        }
      }

      const srcNode = ctx.createBufferSource();
      srcNode.buffer = s.buffer;
      srcNode.loop   = true;
      srcNode.connect(s.gain);
      srcNode.start(0);

      s.node    = srcNode;
      s.playing = true;
      s.cardEl.classList.add('active');
      s.playBtn.innerHTML = getIconSvg('pause');
      s.playBtn.setAttribute('aria-label', `Pause ${s.name}`);
    } else {
      if (s.node) {
        try { s.node.stop(); s.node.disconnect(); } catch (_) {}
        s.node = null;
      }
      s.playing = false;
      s.cardEl.classList.remove('active');
      s.playBtn.innerHTML = getIconSvg('play');
      s.playBtn.setAttribute('aria-label', `Play ${s.name}`);
    }

    updateMasterDeckState();
  }

  // =========================================================================
  // Idle Preloader — silently pre-fetches raw bytes for smallest files
  // while the browser has nothing better to do
  // =========================================================================

  function initIdlePreload() {
    // requestIdleCallback may not be in all environments
    const idle = window.requestIdleCallback || ((cb) => setTimeout(cb, 2000));

    const queue = [...IDLE_PRELOAD_IDS];

    function preloadNext() {
      if (queue.length === 0) return;
      const id = queue.shift();
      const s  = sounds[id];

      // Skip if already decoded, pre-fetched, or synthesized
      if (!s || s.buffer || s._rawBuffer || s.synthesized) {
        preloadNext(); return;
      }

      idle(() => {
        fetch(s.src)
          .then(r => {
            if (!r.ok) throw new Error(`HTTP ${r.status}`);
            return r.arrayBuffer();
          })
          .then(buf => {
            // Only store if the buffer wasn't decoded via user action in the meantime
            if (!s.buffer) s._rawBuffer = buf;
            // Small delay before next fetch so we don't block anything
            setTimeout(preloadNext, 150);
          })
          .catch(() => setTimeout(preloadNext, 500)); // gracefully skip on error
      }, { timeout: 8000 });
    }

    preloadNext();
  }

  // =========================================================================
  // Volume
  // =========================================================================

  function setSoundVolume(s, vol, updateSlider = true) {
    vol  = Math.max(0, Math.min(1, parseFloat(vol)));
    s.vol = vol;
    const effectiveVol = (soloMode !== null && soloMode !== s.id) ? 0 : vol;
    if (s.gain && audioCtx) {
      s.gain.gain.setTargetAtTime(effectiveVol, audioCtx.currentTime, 0.03);
    }
    if (updateSlider && s.sliderEl) {
      s.sliderEl.value = vol;
      updateSliderFill(s.sliderEl);
    }
    if (s.volTextEl) s.volTextEl.textContent = `${Math.round(vol * 100)}%`;
    saveSoundVols();
  }

  function setMasterVolume(vol) {
    vol = Math.max(0, Math.min(1, parseFloat(vol)));
    if (masterGain && audioCtx) {
      masterGain.gain.setTargetAtTime(vol, audioCtx.currentTime, 0.02);
    }
    if (dom.masterVolume) { dom.masterVolume.value = vol; updateSliderFill(dom.masterVolume); }
    if (dom.masterVolPct) dom.masterVolPct.textContent = `${Math.round(vol * 100)}%`;

    if (vol === 0) {
      isMuted = true;
      if (dom.btnMute) dom.btnMute.innerHTML = getIconSvg('volume-x');
    } else {
      isMuted = false;
      if (dom.btnMute) dom.btnMute.innerHTML = vol > 0.5 ? getIconSvg('volume-2') : getIconSvg('volume-1');
      prevVolume = vol;
      localStorage.setItem(LS_VOL, vol);
    }
  }

  function toggleMasterMute() {
    getAudioContext();
    if (isMuted) setMasterVolume(prevVolume > 0 ? prevVolume : 0.5);
    else { prevVolume = parseFloat(dom.masterVolume?.value) || 0.5; setMasterVolume(0); }
  }

  function getActiveSounds() {
    return Object.values(sounds).filter(s => s.playing);
  }

  // =========================================================================
  // Master play — with 1-second fade-in on resume
  // =========================================================================

  async function toggleMasterPlay() {
    getAudioContext();
    const active = getActiveSounds();

    if (active.length > 0) {
      activeMixCache = active.map(s => s.id);
      for (const s of active) await toggleSound(s, false);
    } else {
      let toPlayIds = activeMixCache.length > 0
        ? activeMixCache
        : Object.values(sounds).filter(s => s.vol > 0).map(s => s.id);

      const isDefault = toPlayIds.length === 0;
      if (isDefault) toPlayIds = ['rain', 'wind'];

      // Smooth fade-in from silence
      const currentVol = parseFloat(dom.masterVolume?.value) || prevVolume || 0.5;
      if (masterGain && audioCtx && !isMuted) {
        masterGain.gain.cancelScheduledValues(audioCtx.currentTime);
        masterGain.gain.setValueAtTime(0, audioCtx.currentTime);
        masterGain.gain.linearRampToValueAtTime(currentVol, audioCtx.currentTime + 1.0);
      }

      for (const id of toPlayIds) {
        if (sounds[id]) await toggleSound(sounds[id], true);
      }

      if (isDefault) showToast('▶ Started Rain + Wind — click any card to customize');
    }
    updateMasterDeckState();
  }

  async function stopAllSounds() {
    cancelSleepTimer(false);
    for (const s of Object.values(sounds)) {
      if (s.playing) await toggleSound(s, false);
    }
    activeMixCache = [];
    updateMasterDeckState();
  }

  // =========================================================================
  // Master deck state — with cached DOM refs + page title update
  // =========================================================================

  function updateMasterDeckState() {
    const active = getActiveSounds();
    if (active.length > 0) {
      dom.btnMasterPlay.classList.add('playing');
      dom.btnMasterPlay.innerHTML = getIconSvg('pause-large');
      dom.btnMasterPlay.setAttribute('aria-label', 'Pause Master Mix');
      dom.masterStatus.textContent = `${active.length} sound${active.length === 1 ? '' : 's'} playing`;
      dom.visualizerContainer.classList.add('playing');
      dom.visualizerStatusText.textContent = '';
      document.title = `▶ Noisee — ${active.map(s => s.name).join(' + ')}`;
    } else {
      dom.btnMasterPlay.classList.remove('playing');
      dom.btnMasterPlay.innerHTML = getIconSvg('play-large');
      dom.btnMasterPlay.setAttribute('aria-label', 'Play Master Mix');
      dom.masterStatus.textContent = 'Ready to play';
      dom.visualizerContainer.classList.remove('playing');
      dom.visualizerStatusText.textContent = 'Quiet';
      document.title = 'Noisee — Ambient Soundscape Studio';
    }
  }

  // =========================================================================
  // Per-sound volume persistence
  // =========================================================================

  function saveSoundVols() {
    const vols = {};
    for (const id in sounds) vols[id] = sounds[id].vol;
    localStorage.setItem(LS_SOUND_VOLS, JSON.stringify(vols));
  }

  function loadSoundVols() {
    try { return JSON.parse(localStorage.getItem(LS_SOUND_VOLS) || '{}'); }
    catch (_) { return {}; }
  }

  function resetAllVolumes() {
    for (const id in sounds) setSoundVolume(sounds[id], sounds[id].defaultVol);
    showToast('🔄 Volumes reset to defaults');
  }

  // =========================================================================
  // Slider fill
  // =========================================================================

  function updateSliderFill(slider) {
    const min = parseFloat(slider.min) || 0;
    const max = parseFloat(slider.max) || 1;
    const val = parseFloat(slider.value) || 0;
    slider.style.setProperty('--slider-pct', `${((val - min) / (max - min)) * 100}%`);
  }

  // =========================================================================
  // Visualizer
  // =========================================================================

  function initVisualizer() {
    const canvas = document.getElementById('visualizerCanvas');
    if (!canvas || !analyserNode) return;

    const ctx2d      = canvas.getContext('2d');
    const bufLen     = analyserNode.frequencyBinCount;
    const dataArray  = new Uint8Array(bufLen);

    function resize() {
      canvas.width  = canvas.parentElement.clientWidth  * window.devicePixelRatio;
      canvas.height = canvas.parentElement.clientHeight * window.devicePixelRatio;
    }
    window.addEventListener('resize', resize);
    resize();

    let waveOffset = 0;

    function render() {
      requestAnimationFrame(render);
      const w = canvas.width, h = canvas.height;
      ctx2d.clearRect(0, 0, w, h);
      const hasActive = getActiveSounds().length > 0;
      const isCliamp  = document.documentElement.getAttribute('data-skin') === 'cliamp';

      if (hasActive) {
        analyserNode.getByteFrequencyData(dataArray);
        const barCount = isCliamp ? 32 : 48, barWidth = w / barCount;

        if (isCliamp) {
          ctx2d.fillStyle = '#33ff66';
        } else {
          const grad = ctx2d.createLinearGradient(0, h, w, 0);
          grad.addColorStop(0, '#38bdf8'); grad.addColorStop(0.5, '#818cf8'); grad.addColorStop(1, '#c084fc');
          ctx2d.fillStyle = grad;
        }

        for (let i = 0; i < barCount; i++) {
          const val = dataArray[Math.floor((i / barCount) * (bufLen / 2))] / 255;
          const bh  = Math.max(4, val * (h * 0.85));
          const x   = i * barWidth;
          if (isCliamp) {
            // Blocky stepped LED-meter segments, no anti-aliased rounding
            ctx2d.fillRect(x + 2, (h - bh) / 2, Math.max(1, barWidth - 5), bh);
          } else {
            ctx2d.beginPath();
            ctx2d.roundRect(x + 2, (h - bh) / 2, Math.max(1, barWidth - 4), bh, 4);
            ctx2d.fill();
          }
        }
      } else {
        waveOffset += 0.02;
        const isLight = document.documentElement.getAttribute('data-theme') === 'light';
        ctx2d.strokeStyle = isCliamp ? 'rgba(51,255,102,0.5)' : (isLight ? 'rgba(0,0,0,0.12)' : 'rgba(255,255,255,0.08)');
        ctx2d.lineWidth   = 2 * window.devicePixelRatio;
        ctx2d.beginPath();
        for (let x = 0; x < w; x += 4) {
          const y = h / 2 + Math.sin(x * 0.015 + waveOffset) * (8 * window.devicePixelRatio);
          x === 0 ? ctx2d.moveTo(x, y) : ctx2d.lineTo(x, y);
        }
        ctx2d.stroke();
      }
    }
    render();
  }

  // =========================================================================
  // Presets
  // =========================================================================

  function loadCustomPresets() {
    try { customPresets = JSON.parse(localStorage.getItem(LS_CUSTOM_PRESETS) || '{}'); }
    catch (_) { customPresets = {}; }
  }

  function saveCustomPresets() {
    localStorage.setItem(LS_CUSTOM_PRESETS, JSON.stringify(customPresets));
  }

  function populatePresetSelect() {
    const select = document.getElementById('presetSelect');
    select.innerHTML = '<option value="" disabled selected>Select a Preset...</option>';

    const builtinGroup = document.createElement('optgroup');
    builtinGroup.label = 'Built-in Presets';
    for (const name in BUILTIN_PRESETS) {
      const opt = document.createElement('option');
      opt.value = `builtin:${name}`; opt.textContent = name;
      builtinGroup.appendChild(opt);
    }
    select.appendChild(builtinGroup);

    if (Object.keys(customPresets).length > 0) {
      const customGroup = document.createElement('optgroup');
      customGroup.label = 'Custom Presets';
      for (const name in customPresets) {
        const opt = document.createElement('option');
        opt.value = `custom:${name}`; opt.textContent = name;
        customGroup.appendChild(opt);
      }
      select.appendChild(customGroup);
    }
  }

  // Smooth preset transitions — volumes fade via time constant
  async function applyPreset(presetData, autoPlay = true) {
    getAudioContext();
    const TC = 0.12;
    for (const id in sounds) {
      const s         = sounds[id];
      const targetVol = presetData[id] !== undefined ? presetData[id] : 0;
      s.vol = targetVol;
      ensureSoundGain(id);
      if (s.gain && audioCtx) s.gain.gain.setTargetAtTime(targetVol, audioCtx.currentTime, TC);
      if (s.sliderEl) { s.sliderEl.value = targetVol; updateSliderFill(s.sliderEl); }
      if (s.volTextEl) s.volTextEl.textContent = `${Math.round(targetVol * 100)}%`;
      if (autoPlay) {
        if (targetVol > 0) await toggleSound(s, true);
        else               await toggleSound(s, false);
      }
    }
    saveSoundVols();
  }

  function saveCurrentAsPreset() {
    if (!Object.values(sounds).some(s => s.vol > 0)) {
      showToast('Set at least one sound volume before saving!'); return;
    }
    const modal = document.getElementById('presetNameModal');
    const input = document.getElementById('presetNameInput');
    if (modal && input) { input.value = ''; modal.classList.add('open'); setTimeout(() => input.focus(), 80); }
  }

  function confirmSavePreset(name) {
    if (!name?.trim()) return;
    const presetName = name.trim();
    const config = {};
    for (const s of Object.values(sounds)) { if (s.vol > 0) config[s.id] = s.vol; }
    customPresets[presetName] = config;
    saveCustomPresets();
    populatePresetSelect();
    document.getElementById('presetSelect').value = `custom:${presetName}`;
    showToast(`💾 Preset "${presetName}" saved!`);
  }

  function randomizeMix() {
    getAudioContext();
    const list   = Object.values(sounds);
    const count  = Math.floor(Math.random() * 3) + 2;
    const chosen = [...list].sort(() => 0.5 - Math.random()).slice(0, count);
    for (const s of list) {
      if (chosen.includes(s)) {
        setSoundVolume(s, Math.round((0.25 + Math.random() * 0.55) * 100) / 100);
        toggleSound(s, true);
      } else { setSoundVolume(s, 0); toggleSound(s, false); }
    }
    document.getElementById('presetSelect').value = '';
    showToast(`🎲 Generated balanced ${count}-sound ambient mix`);
  }

  // =========================================================================
  // Solo mode — Alt+click
  // =========================================================================

  function toggleSolo(soundId) {
    if (!sounds[soundId]) return;
    getAudioContext();
    if (soloMode === soundId) {
      soloMode = null;
      for (const id in sounds) {
        const s = sounds[id];
        if (s.gain && audioCtx) s.gain.gain.setTargetAtTime(s.vol, audioCtx.currentTime, 0.1);
        s.cardEl.classList.remove('solo');
      }
      showToast('Solo off — all sounds restored');
    } else {
      soloMode = soundId;
      for (const id in sounds) {
        const s = sounds[id];
        if (id === soundId) {
          if (!s.playing) toggleSound(s, true);
          if (s.gain && audioCtx) s.gain.gain.setTargetAtTime(s.vol, audioCtx.currentTime, 0.1);
          s.cardEl.classList.add('solo');
        } else {
          if (s.gain && audioCtx) s.gain.gain.setTargetAtTime(0, audioCtx.currentTime, 0.1);
          s.cardEl.classList.remove('solo');
        }
      }
      showToast(`🎯 Solo: ${sounds[soundId].name}  •  Alt+click again to exit`);
    }
  }

  // =========================================================================
  // URL Hash Share / Import
  // =========================================================================

  function getShareUrl() {
    const params = [];
    for (const s of Object.values(sounds)) {
      if (s.playing && s.vol > 0) params.push(`${s.id}=${Math.round(s.vol * 100)}`);
    }
    params.push(`master=${Math.round((parseFloat(dom.masterVolume?.value) || 0.5) * 100)}`);
    const url = new URL(window.location.href);
    url.hash  = params.join('&');
    return url.toString();
  }

  function copyShareLink() {
    const url = getShareUrl();
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(url)
        .then(() => showToast('🔗 Soundscape link copied to clipboard!'))
        .catch(() => showShareFallback(url));
    } else {
      showShareFallback(url);
    }
  }

  function showShareFallback(url) {
    const modal    = document.getElementById('shareUrlModal');
    const urlInput = document.getElementById('shareUrlInput');
    if (modal && urlInput) {
      urlInput.value = url;
      modal.classList.add('open');
      setTimeout(() => { urlInput.select(); urlInput.focus(); }, 80);
    }
  }

  function loadMixFromHash() {
    if (!window.location.hash || window.location.hash.length < 2) return false;
    const mixData = {};
    let masterV   = null;
    window.location.hash.substring(1).split('&').forEach(pair => {
      const [k, v] = pair.split('=');
      if (k === 'master') masterV = parseInt(v, 10) / 100;
      else if (v !== undefined) mixData[k] = parseInt(v, 10) / 100;
    });
    if (masterV !== null && !isNaN(masterV)) setMasterVolume(masterV);
    if (Object.keys(mixData).length > 0) { applyPreset(mixData, true); showToast('Loaded shared soundscape mix'); return true; }
    return false;
  }

  // =========================================================================
  // Sleep Timer
  // =========================================================================

  function startSleepTimer(minutes, fadeOut = true) {
    cancelSleepTimer(false);
    sleepTimerEndsAt = Date.now() + minutes * 60 * 1000;
    sleepInitialVol  = parseFloat(dom.masterVolume?.value) || prevVolume || 0.5;

    const badge = document.getElementById('timerStatusBadge');
    const countdown = document.getElementById('sleepCountdownDisplay');
    if (badge)     badge.style.display     = 'inline-flex';
    if (countdown) countdown.style.display = 'block';

    sleepTimerInterval = setInterval(() => {
      if (!sleepTimerEndsAt) { clearInterval(sleepTimerInterval); return; }
      const remainingMs = sleepTimerEndsAt - Date.now();

      if (remainingMs <= 0) {
        const initVol = sleepInitialVol;
        cancelSleepTimer(false);
        stopAllSounds();
        if (initVol !== null) setMasterVolume(initVol);
        showToast('🌙 Sleep timer finished. All sounds stopped.');
        return;
      }

      const s   = Math.ceil(remainingMs / 1000);
      const fmt = `${Math.floor(s / 60)}:${(s % 60 < 10 ? '0' : '')}${s % 60}`;
      const sleepEl = document.getElementById('sleepTimeRemaining');
      const badgeEl = document.getElementById('timerBadgeText');
      if (sleepEl) sleepEl.textContent = fmt;
      if (badgeEl) badgeEl.textContent = fmt;

      if (fadeOut && s <= 30 && masterGain && audioCtx) {
        masterGain.gain.setTargetAtTime(sleepInitialVol * (s / 30), audioCtx.currentTime, 0.1);
      }
    }, 1000);

    showToast(`🌙 Sleep timer set for ${minutes} minute${minutes === 1 ? '' : 's'}`);
  }

  function cancelSleepTimer(showNotification = true) {
    if (sleepTimerInterval) { clearInterval(sleepTimerInterval); sleepTimerInterval = null; }
    sleepTimerEndsAt = null; sleepInitialVol = null;
    const badge = document.getElementById('timerStatusBadge');
    const countdown = document.getElementById('sleepCountdownDisplay');
    if (badge)     badge.style.display     = 'none';
    if (countdown) countdown.style.display = 'none';
    if (showNotification) showToast('Sleep timer cancelled');
  }

  // =========================================================================
  // Pomodoro — timestamp-based
  // =========================================================================

  function getPomodoroTotalSecs() {
    const workEl  = document.getElementById('pomodoroWorkMinutes');
    const breakEl = document.getElementById('pomodoroBreakMinutes');
    return pomodoroMode === 'work'
      ? (parseInt(workEl?.value, 10) || 25) * 60
      : (parseInt(breakEl?.value, 10) || 5) * 60;
  }

  function startPomodoro() {
    clearInterval(pomodoroInterval);
    pomodoroStartTime = Date.now();
    pomodoroInterval = setInterval(() => {
      pomodoroTimeLeft = Math.max(0, pomodoroRemainingAtPause - Math.floor((Date.now() - pomodoroStartTime) / 1000));
      updatePomodoroDisplay();
      if (pomodoroTimeLeft <= 0) {
        clearInterval(pomodoroInterval); pomodoroInterval = null; pomodoroStartTime = null;
        playChime();
        pomodoroMode = pomodoroMode === 'work' ? 'break' : 'work';
        showToast(pomodoroMode === 'break' ? '☕ Focus done! Take a break.' : '🎯 Break over! Back to focus.');
        pomodoroRemainingAtPause = getPomodoroTotalSecs();
        pomodoroTimeLeft         = pomodoroRemainingAtPause;
        updatePomodoroDisplay();
        startPomodoro();
      }
    }, 250);
    document.getElementById('btnStartPomodoro').textContent = 'Pause Focus';
  }

  function pausePomodoro() {
    clearInterval(pomodoroInterval); pomodoroInterval = null;
    pomodoroRemainingAtPause = pomodoroTimeLeft; pomodoroStartTime = null;
    document.getElementById('btnStartPomodoro').textContent = 'Resume Focus';
  }

  function resetPomodoro() {
    clearInterval(pomodoroInterval); pomodoroInterval = null; pomodoroStartTime = null;
    pomodoroMode = 'work'; pomodoroRemainingAtPause = getPomodoroTotalSecs(); pomodoroTimeLeft = pomodoroRemainingAtPause;
    updatePomodoroDisplay();
    document.getElementById('btnStartPomodoro').textContent = 'Start Focus';
  }

  function updatePomodoroDisplay() {
    const m = Math.floor(pomodoroTimeLeft / 60), s = pomodoroTimeLeft % 60;
    const digitsEl = document.getElementById('pomodoroTimeDigits');
    const labelEl  = document.getElementById('pomodoroModeLabel');
    if (digitsEl) digitsEl.textContent = `${m}:${s < 10 ? '0' : ''}${s}`;
    if (labelEl)  labelEl.textContent  = pomodoroMode === 'work' ? 'Focus Session' : 'Rest Break';
    const ring = document.getElementById('pomodoroProgressRing');
    if (ring) {
      const total = getPomodoroTotalSecs();
      const circ  = 2 * Math.PI * 54; // r=54
      ring.style.strokeDasharray  = `${circ}`;
      ring.style.strokeDashoffset = `${circ * (1 - (total > 0 ? pomodoroTimeLeft / total : 1))}`;
      ring.style.stroke = pomodoroMode === 'work' ? 'var(--accent-cyan)' : 'var(--accent-emerald)';
    }
  }

  function playChime() {
    try {
      const ctx  = getAudioContext();
      const osc  = ctx.createOscillator(), gain = ctx.createGain();
      osc.type = 'sine';
      osc.frequency.setValueAtTime(587.33, ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(880, ctx.currentTime + 0.3);
      gain.gain.setValueAtTime(0.3, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.2);
      osc.connect(gain); gain.connect(ctx.destination);
      osc.start(); osc.stop(ctx.currentTime + 1.2);
    } catch (_) {}
  }

  // =========================================================================
  // Drag and Drop Reordering
  // =========================================================================

  function initDragAndDrop() {
    const grid = document.getElementById('soundsGrid');
    let draggedCard = null, isDragging = false;

    grid.addEventListener('dragstart', (e) => {
      const card = e.target.closest('.sound-card');
      if (!card || e.target.tagName === 'INPUT' || e.target.closest('input') ||
          e.target.closest('button') || e.target.closest('.slider-container')) {
        e.preventDefault(); return;
      }
      draggedCard = card; isDragging = true;
      card.classList.add('dragging');
      e.dataTransfer.effectAllowed = 'move';
      e.dataTransfer.setData('text/plain', card.dataset.id);
    });

    grid.addEventListener('dragover', (e) => {
      e.preventDefault(); if (!draggedCard) return;
      e.dataTransfer.dropEffect = 'move';
      const target = e.target.closest('.sound-card');
      if (!target || target === draggedCard) return;
      const rect = target.getBoundingClientRect();
      grid.insertBefore(draggedCard, (e.clientY - rect.top) / (rect.bottom - rect.top) > 0.5 ? target.nextSibling : target);
    });

    grid.addEventListener('dragenter', (e) => {
      e.preventDefault();
      const t = e.target.closest('.sound-card');
      if (t && t !== draggedCard) t.classList.add('drag-over');
    });
    grid.addEventListener('dragleave', (e) => { const t = e.target.closest('.sound-card'); if (t) t.classList.remove('drag-over'); });
    grid.addEventListener('drop',    (e) => { e.preventDefault(); cleanupDrag(); });
    grid.addEventListener('dragend', ()  => cleanupDrag());

    function cleanupDrag() {
      if (draggedCard) { draggedCard.classList.remove('dragging'); draggedCard = null; }
      grid.querySelectorAll('.sound-card').forEach(c => c.classList.remove('drag-over'));
      saveSoundOrder(); isDragging = false;
    }
    grid._isDragging = () => isDragging;
  }

  function saveSoundOrder() {
    localStorage.setItem(LS_ORDER, JSON.stringify(
      Array.from(document.querySelectorAll('.sound-card')).map(c => c.dataset.id)));
  }

  function applySavedOrder() {
    try {
      const order = JSON.parse(localStorage.getItem(LS_ORDER) || 'null');
      if (!order) return;
      const grid = document.getElementById('soundsGrid');
      order.forEach(id => { const c = grid.querySelector(`.sound-card[data-id="${id}"]`); if (c) grid.appendChild(c); });
    } catch (e) { console.warn('Failed to load saved order:', e); }
  }

  // =========================================================================
  // Toast Notifications
  // =========================================================================

  function showToast(message, duration = 3000) {
    const container = document.getElementById('toastContainer');
    const toast = document.createElement('div');
    toast.className = 'toast'; toast.textContent = message;
    container.appendChild(toast);
    setTimeout(() => {
      toast.classList.add('fade-out');
      toast.addEventListener('animationend', () => toast.remove());
    }, duration);
  }

  // =========================================================================
  // SVG Icons
  // =========================================================================

  function getIconSvg(name) {
    const icons = {
      'play':        '<svg viewBox="0 0 24 24"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>',
      'pause':       '<svg viewBox="0 0 24 24"><rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect></svg>',
      'play-large':  '<svg viewBox="0 0 24 24"><polygon points="6 4 20 12 6 20 6 4"></polygon></svg>',
      'pause-large': '<svg viewBox="0 0 24 24"><rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect></svg>',
      'volume-2':    '<svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M19.07 4.93a10 10 0 0 1 0 14.14M15.54 8.46a5 5 0 0 1 0 7.07"></path></svg>',
      'volume-1':    '<svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path></svg>',
      'volume-x':    '<svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><line x1="23" y1="9" x2="17" y2="15"></line><line x1="17" y1="9" x2="23" y2="15"></line></svg>',
      'grip':        '<svg viewBox="0 0 24 24"><circle cx="9" cy="6" r="1.5"></circle><circle cx="15" cy="6" r="1.5"></circle><circle cx="9" cy="12" r="1.5"></circle><circle cx="15" cy="12" r="1.5"></circle><circle cx="9" cy="18" r="1.5"></circle><circle cx="15" cy="18" r="1.5"></circle></svg>'
    };
    return icons[name] || '';
  }

  // =========================================================================
  // App Initialization
  // =========================================================================

  function initApp() {
    loadCustomPresets();
    const savedVols = loadSoundVols();

    SOUNDS_DEF.forEach(def => {
      const cardEl    = document.querySelector(`.sound-card[data-id="${def.id}"]`);
      if (!cardEl) return;

      const playBtn   = cardEl.querySelector('.btn-track-play');
      const sliderEl  = cardEl.querySelector('.sound-vol-slider');
      const volTextEl = cardEl.querySelector('.track-vol-text');
      const handleEl  = cardEl.querySelector('.drag-handle');
      if (handleEl) handleEl.innerHTML = getIconSvg('grip');

      const restoredVol = savedVols[def.id] !== undefined ? savedVols[def.id] : def.defaultVol;

      sounds[def.id] = {
        ...def, gain: null, buffer: null, node: null,
        playing: false, vol: restoredVol,
        cardEl, playBtn, sliderEl, volTextEl
      };

      if (sliderEl) { sliderEl.value = restoredVol; updateSliderFill(sliderEl); }
      if (volTextEl) volTextEl.textContent = `${Math.round(restoredVol * 100)}%`;

      playBtn.addEventListener('click', (e) => { e.stopPropagation(); toggleSound(sounds[def.id]); });

      sliderEl.setAttribute('draggable', 'false');
      sliderEl.addEventListener('pointerdown', (e) => { e.stopPropagation(); cardEl.setAttribute('draggable', 'false'); });
      sliderEl.addEventListener('mousedown',   (e) => { e.stopPropagation(); cardEl.setAttribute('draggable', 'false'); });
      sliderEl.addEventListener('click',       (e) => e.stopPropagation());
      sliderEl.addEventListener('input', (e) => {
        ensureSoundGain(def.id);
        setSoundVolume(sounds[def.id], e.target.value, false);
        updateSliderFill(e.target);
        document.getElementById('presetSelect').value = '';
      });

      cardEl.addEventListener('click', (e) => {
        const grid = document.getElementById('soundsGrid');
        if (grid._isDragging?.()) return;
        if (e.target.closest('input') || e.target.closest('button') ||
            e.target.closest('.slider-container') || e.target.closest('.sound-ctrl-row') ||
            e.target.closest('.drag-handle')) return;
        if (e.altKey) { e.preventDefault(); toggleSolo(def.id); return; }
        toggleSound(sounds[def.id]);
      });
    });

    window.addEventListener('pointerup', () => document.querySelectorAll('.sound-card').forEach(c => c.setAttribute('draggable', 'true')));
    window.addEventListener('mouseup',   () => document.querySelectorAll('.sound-card').forEach(c => c.setAttribute('draggable', 'true')));

    applySavedOrder();
    initDragAndDrop();

    // Cache DOM refs
    const masterSlider = document.getElementById('masterVolume');
    dom = {
      masterVolume:         masterSlider,
      masterVolPct:         document.getElementById('masterVolPct'),
      btnMute:              document.getElementById('btnMute'),
      btnMasterPlay:        document.getElementById('btnMasterPlay'),
      masterStatus:         document.getElementById('masterStatus'),
      visualizerContainer:  document.querySelector('.visualizer-container'),
      visualizerStatusText: document.getElementById('visualizerStatusText'),
    };

    const savedMasterVol   = localStorage.getItem(LS_VOL);
    const initialMasterVol = savedMasterVol !== null ? parseFloat(savedMasterVol) : 0.5;
    masterSlider.setAttribute('draggable', 'false');
    masterSlider.addEventListener('mousedown',   (e) => e.stopPropagation());
    masterSlider.addEventListener('pointerdown', (e) => e.stopPropagation());
    masterSlider.value = initialMasterVol;
    dom.masterVolPct.textContent = `${Math.round(initialMasterVol * 100)}%`;
    updateSliderFill(masterSlider);
    prevVolume = initialMasterVol;

    masterSlider.addEventListener('input', (e) => {
      const vol = parseFloat(e.target.value);
      updateSliderFill(e.target);
      dom.masterVolPct.textContent = `${Math.round(vol * 100)}%`;
      prevVolume = vol;
      localStorage.setItem(LS_VOL, vol);
      if (masterGain && audioCtx) masterGain.gain.setTargetAtTime(vol, audioCtx.currentTime, 0.02);
      isMuted = vol === 0;
    });

    document.getElementById('btnMute').addEventListener('click', toggleMasterMute);
    document.getElementById('btnMasterPlay').addEventListener('click', toggleMasterPlay);
    document.getElementById('btnRandomize').addEventListener('click', randomizeMix);
    document.getElementById('btnShareMix').addEventListener('click', copyShareLink);
    document.getElementById('btnSavePreset').addEventListener('click', saveCurrentAsPreset);
    document.getElementById('btnResetVolumes')?.addEventListener('click', resetAllVolumes);

    populatePresetSelect();
    document.getElementById('presetSelect').addEventListener('change', () => {
      const val = document.getElementById('presetSelect').value;
      if (val.startsWith('builtin:')) {
        const name = val.replace('builtin:', '');
        if (BUILTIN_PRESETS[name]) { applyPreset(BUILTIN_PRESETS[name], true); showToast(`Applied preset: ${name}`); }
      } else if (val.startsWith('custom:')) {
        const name = val.replace('custom:', '');
        if (customPresets[name]) { applyPreset(customPresets[name], true); showToast(`Applied: ${name}`); }
      }
    });

    initTheme();
    initSkin();
    initModals();
    initKeyboardShortcuts();
    loadMixFromHash();
    updatePomodoroDisplay();

    // ✅ Start idle preloading AFTER the UI is ready — doesn't block anything
    initIdlePreload();

    if ('serviceWorker' in navigator) {
      window.addEventListener('load', () => {
        navigator.serviceWorker.register('./sw.js')
          .then(r => console.log('SW:', r.scope))
          .catch(e => console.warn('SW failed:', e));
      });
    }
  }

  // =========================================================================
  // Modal Logic
  // =========================================================================

  function initModals() {
    const timerModal      = document.getElementById('timerModal');
    const shortcutsModal  = document.getElementById('shortcutsModal');
    const presetNameModal = document.getElementById('presetNameModal');
    const shareUrlModal   = document.getElementById('shareUrlModal');

    document.getElementById('btnOpenTimer').addEventListener('click', () => timerModal.classList.add('open'));
    document.getElementById('btnOpenShortcuts').addEventListener('click', () => shortcutsModal.classList.add('open'));

    document.querySelectorAll('.modal-backdrop').forEach(el => {
      el.addEventListener('click', (e) => {
        if (e.target === el || e.target.closest('.modal-close')) el.classList.remove('open');
      });
    });

    if (presetNameModal) {
      const nameInput = document.getElementById('presetNameInput');
      document.getElementById('btnConfirmSavePreset').addEventListener('click', () => {
        confirmSavePreset(nameInput.value); presetNameModal.classList.remove('open');
      });
      document.getElementById('btnCancelSavePreset').addEventListener('click', () => presetNameModal.classList.remove('open'));
      nameInput.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') { confirmSavePreset(nameInput.value); presetNameModal.classList.remove('open'); }
      });
    }

    if (shareUrlModal) {
      const urlInput = document.getElementById('shareUrlInput');
      const btnCopy  = document.getElementById('btnCopyShareUrl');
      if (btnCopy && urlInput) {
        btnCopy.addEventListener('click', () => {
          urlInput.select();
          try { document.execCommand('copy'); showToast('🔗 Link copied!'); } catch (_) {}
          shareUrlModal.classList.remove('open');
        });
      }
    }

    const tabs = document.querySelectorAll('.modal-tab-btn');
    tabs.forEach(tab => {
      tab.addEventListener('click', () => {
        tabs.forEach(t => t.classList.remove('active'));
        document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));
        tab.classList.add('active');
        document.getElementById(tab.dataset.tab)?.classList.add('active');
      });
    });

    let selectedSleepMinutes = 30;
    document.querySelectorAll('.timer-pill-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        document.querySelectorAll('.timer-pill-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        selectedSleepMinutes = parseInt(btn.dataset.min, 10);
        document.getElementById('customSleepMinutes').value = '';
      });
    });
    document.getElementById('customSleepMinutes').addEventListener('input', (e) => {
      document.querySelectorAll('.timer-pill-btn').forEach(b => b.classList.remove('active'));
      selectedSleepMinutes = parseInt(e.target.value, 10) || 0;
    });
    document.getElementById('btnStartSleepTimer').addEventListener('click', () => {
      const customVal = parseInt(document.getElementById('customSleepMinutes').value, 10);
      const mins      = customVal > 0 ? customVal : selectedSleepMinutes;
      if (mins <= 0) { showToast('Please select a duration first'); return; }
      if (getActiveSounds().length === 0) showToast('⚠️ No sounds playing — timer set, start sounds when ready');
      startSleepTimer(mins, document.getElementById('chkSleepFadeOut').checked);
      timerModal.classList.remove('open');
    });
    document.getElementById('btnCancelSleepTimer').addEventListener('click', () => {
      const was = sleepTimerInterval !== null;
      cancelSleepTimer(false);
      showToast(was ? 'Sleep timer cancelled' : 'No active sleep timer');
    });

    document.getElementById('btnStartPomodoro').addEventListener('click', () => {
      pomodoroInterval ? pausePomodoro() : startPomodoro();
    });
    document.getElementById('btnResetPomodoro').addEventListener('click', resetPomodoro);

    const workInput  = document.getElementById('pomodoroWorkMinutes');
    const breakInput = document.getElementById('pomodoroBreakMinutes');
    if (workInput)  workInput.addEventListener('change',  () => { if (!pomodoroInterval) resetPomodoro(); });
    if (breakInput) breakInput.addEventListener('change', () => { if (!pomodoroInterval && pomodoroMode === 'break') resetPomodoro(); });
  }

  // =========================================================================
  // Theme
  // =========================================================================

  function applyTheme(theme) {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem(LS_THEME, theme);
    document.querySelector('meta[name="theme-color"]')?.setAttribute('content', theme === 'light' ? '#f8fafc' : '#07090e');
  }

  function toggleTheme() {
    const next = (document.documentElement.getAttribute('data-theme') || 'dark') === 'light' ? 'dark' : 'light';
    applyTheme(next);
    showToast(next === 'light' ? '☀️ Switched to Light Mode' : '🌙 Switched to Dark Mode');
  }

  function initTheme() {
    const saved = localStorage.getItem(LS_THEME);
    applyTheme(saved || (window.matchMedia?.('(prefers-color-scheme: light)').matches ? 'light' : 'dark'));
    document.getElementById('btnToggleTheme')?.addEventListener('click', toggleTheme);
  }

  // =========================================================================
  // Skins
  // =========================================================================

  function applySkin(skin) {
    document.documentElement.setAttribute('data-skin', skin);
    localStorage.setItem(LS_SKIN, skin);

    document.querySelectorAll('.skin-option').forEach(opt => {
      opt.classList.toggle('active', opt.dataset.skin === skin);
    });

    // Cliamp is a fixed phosphor-green terminal palette — the light/dark toggle doesn't apply
    const themeBtn = document.getElementById('btnToggleTheme');
    if (skin === 'cliamp') {
      if (themeBtn) themeBtn.style.display = 'none';
      document.documentElement.setAttribute('data-theme', 'dark');
    } else {
      if (themeBtn) themeBtn.style.display = '';
      const savedTheme = localStorage.getItem(LS_THEME);
      applyTheme(savedTheme || (window.matchMedia?.('(prefers-color-scheme: light)').matches ? 'light' : 'dark'));
    }
  }

  function initSkin() {
    const saved = localStorage.getItem(LS_SKIN) || 'default';
    applySkin(saved);

    document.getElementById('btnOpenSkins')?.addEventListener('click', () => {
      document.getElementById('skinModal')?.classList.add('open');
    });

    document.querySelectorAll('.skin-option').forEach(opt => {
      opt.addEventListener('click', () => {
        applySkin(opt.dataset.skin);
        showToast(`Skin set to ${opt.querySelector('.skin-option-name')?.textContent || opt.dataset.skin}`);
        document.getElementById('skinModal')?.classList.remove('open');
      });
    });
  }

  // =========================================================================
  // Keyboard Shortcuts
  // =========================================================================

  function initKeyboardShortcuts() {
    window.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        const open = document.querySelectorAll('.modal-backdrop.open');
        if (open.length > 0) { e.preventDefault(); open.forEach(m => m.classList.remove('open')); return; }
      }
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'SELECT' || e.target.tagName === 'TEXTAREA') return;

      if      (e.code === 'Space')               { e.preventDefault(); toggleMasterPlay(); }
      else if (e.key === 'm' || e.key === 'M')   toggleMasterMute();
      else if (e.key === 'r' || e.key === 'R')   randomizeMix();
      else if (e.key === 's' || e.key === 'S' || e.key === '0') stopAllSounds();
      else if (e.key === 't' || e.key === 'T')   document.getElementById('timerModal').classList.toggle('open');
      else if (e.key === 'd' || e.key === 'D')   toggleTheme();
      else if (e.key === '?')                    document.getElementById('shortcutsModal').classList.toggle('open');
      else if (e.key >= '1' && e.key <= '8') {
        const def = SOUNDS_DEF[parseInt(e.key, 10) - 1];
        if (def && sounds[def.id]) toggleSound(sounds[def.id]);
      }
    });
  }

  // Boot
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initApp);
  } else {
    initApp();
  }
})();
